menu:
- {name: 'about', url: '/about'}
- {name: 'contact', url: '/contact'}

contacts:
- {name: 'Bassett-Vore LFP', institution_address: '4010 Ada Road, Lima, OH 45801', email: 'steve.baskauf@gmail.com', image: 'assets/img/contact.jpg'}
